namespace: openshift-gitops

resources:
- ../base

patches:
- target:
    kind: Application
    name: kong
  patch: |-
    - op: replace
      path: /metadata/name
      value: kong-cp
- target:
    kind: Application
    name: kong
  patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: kong-cp
    spec:
      source:
        helm:
          valueFiles: ["values-cp.yaml"]
