namespace: openshift-gitops

resources:
- ../base

patches:
- target:
    kind: Application
    name: kong
  patch: |-
    - op: replace
      path: /metadata/name
      value: kong-cp
- target:
    kind: Application
    name: kong
  patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: kong-cp
    spec:
      source:
        helm:
          values: |
            ingressController:
              enabled: false
            image:
              repository: kong/kong-gateway
              tag: 2.8.0.0-alpine
              unifiedRepoTag: kong/kong-gateway:2.8.0.0-alpine
            env:
              database: "off"
              role: data_plane
              cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
              cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
              lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
              cluster_control_plane: kong-kong-cluster.kong.svc.cluster.local:8005
              cluster_telemetry_endpoint: kong-kong-clustertelemetry.kong.svc.cluster.local:8006
              status_listen: 0.0.0.0:8100
            proxy:
              enabled: true
              type: ClusterIP
            secretVolumes: 
              - kong-cluster-cert
            enterprise:
              enabled: true
              license_secret: kong-enterprise-license
              portal:
                enabled: false
              rbac:
                enabled: false
              smtp:
                enabled: false
            admin:
              enabled: false
            manager:
              enabled: false
            portal:
              enabled: false
            portalapi:
              enabled: false  
