apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kong-prom
  namespace: kong
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: kong
      port: web
  podMonitorSelector: {}
  probeSelector: {}
  replicas: 1
  ruleSelector: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      app: kong
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kong
  name: kong-status
  namespace: kong
spec:
  endpoints:
  - interval: 30s
    port: kong-status
  selector:
    matchLabels:
      kong-metrics: kong-admin
