apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: opa-authorization-plugin
  namespace: kuma-app
config: 
  opa_host: opa.kong-opa.svc
  opa_port: 8181
  opa_path: /v1/data/kongdemo
plugin: opa