apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: keycloak-auth-plugin
  namespace: kuma-app
config: 
  auth_methods:
  - authorization_code
  - session
  - bearer
  issuer: https://keycloak-kong-keycloak.$OCP_DOMAIN/auth/realms/kong
  client_id:
  - kuma-demo-client
  client_secret:
  - client-secret
plugin: openid-connect