{
 "title": "Kong Mesh OPA",
 "description": "Statistics of a single Dataplane in Kuma Service Mesh",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mesh",
    "label": "Mesh",
    "query": {
     "query": "label_values(envoy_server_live, mesh)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(envoy_server_live{mesh=\"$mesh\"}, kuma_io_service)"
    }
   },
   {
    "name": "dataplane",
    "label": "Dataplane",
    "query": {
     "query": "label_values(envoy_server_live{mesh=\"$mesh\",kuma_io_service=\"$service\"}, dataplane)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "External Authorization decisions on incoming HTTP requests to selected data plane proxy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_http_ext_authz_denied{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "Denied - {{ envoy_http_conn_manager_prefix }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_ok{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "OK - {{ envoy_http_conn_manager_prefix }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_disabled{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "Disabled - {{ envoy_http_conn_manager_prefix }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_error{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "Error - {{ envoy_http_conn_manager_prefix }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_failure_mode_allowed{dataplane=\"$dataplane\",mesh=\"$mesh\"}[1m])",
     "legendFormat": "Failure mode allowed - {{ envoy_http_conn_manager_prefix }}"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "External Authorization decisions on incoming HTTP requests to the all plane proxies of selected service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_http_ext_authz_denied{mesh=\"$mesh\",kuma_io_service=\"$service\"}[1m])",
     "legendFormat": "Denied - {{ dataplane }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_ok{mesh=\"$mesh\",kuma_io_service=\"$service\"}[1m])",
     "legendFormat": "OK - {{ dataplane }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_disabled{mesh=\"$mesh\",kuma_io_service=\"$service\"}[1m])",
     "legendFormat": "Disabled - {{ dataplane }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_error{mesh=\"$mesh\",kuma_io_service=\"$service\"}[1m])",
     "legendFormat": "Error - {{ dataplane }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_failure_mode_allowed{mesh=\"$mesh\",kuma_io_service=\"$service\"}[1m])",
     "legendFormat": "Failure mode allowed - {{ dataplane }}"
    }
   ]
  },
  { "title": "Mesh", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "External Authorization decisions on incoming HTTP requests to the all plane proxies in selected Mesh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_http_ext_authz_denied{mesh=\"$mesh\"}[1m])",
     "legendFormat": "Denied - {{ kuma_io_service }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_ok{mesh=\"$mesh\"}[1m])",
     "legendFormat": "OK - {{ kuma_io_service }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_disabled{mesh=\"$mesh\"}[1m])",
     "legendFormat": "Disabled - {{ kuma_io_service }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_error{mesh=\"$mesh\"}[1m])",
     "legendFormat": "Error - {{ kuma_io_service }}"
    },
    {
     "expr": "irate(envoy_http_ext_authz_failure_mode_allowed{mesh=\"$mesh\"}[1m])",
     "legendFormat": "Failure mode allowed - {{ kuma_io_service }}"
    }
   ]
  }
 ]
}