{
 "title": "Kuma Dataplane",
 "description": "Statistics of a single Dataplane in Kuma Service Mesh",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mesh",
    "label": "Mesh",
    "query": {
     "query": "label_values(envoy_server_live, mesh)"
    }
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "label_values(envoy_server_live{mesh=\"$mesh\"}, kuma_io_zone)"
    }
   },
   {
    "name": "dataplane",
    "label": "Dataplane",
    "query": {
     "query": "label_values(envoy_server_live{mesh=\"$mesh\",kuma_io_zone=~\"$zone\"}, dataplane)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"} OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "envoy_server_uptime{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "envoy_server_memory_heap_size{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "envoy_server_memory_allocated{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}"
    }
   ]
  },
  {
   "title": "Connection to the Control Plane",
   "type": "graph",
   "description": "Note that if Control Plane does not sent FIN segment, Dataplanes can still think that connection is up waiting for new update even that Control Plane is down.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_control_plane_connected_state{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}",
     "legendFormat": "Connected"
    }
   ]
  },
  {
   "title": "Incoming traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections to this Dataplane",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_cluster_upstream_cx_active{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Connection time (P99)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, irate(envoy_cluster_upstream_cx_connect_ms_bucket{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m]))",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Connection length (P99)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, irate(envoy_cluster_upstream_cx_length_ms_bucket{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m]))",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Bytes received from requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m])",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Bytes sent in responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m])",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Traffic permissions",
     "type": "graph",
     "description": "Data is only available if TrafficPermission policy is applied.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_rbac_allowed{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m])",
       "legendFormat": "Allowed - {{listener}}"
      },
      {
       "expr": "irate(envoy_rbac_shadow_allowed{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m])",
       "legendFormat": "Shadow allowed - {{listener}}"
      },
      {
       "expr": "irate(envoy_rbac_denied{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m])",
       "legendFormat": "Denied - {{listener}}"
      },
      {
       "expr": "irate(envoy_rbac_shadow_denied{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m])",
       "legendFormat": "Shadow denied - {{listener}}"
      }
     ]
    },
    {
     "title": "Connection/Requests errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_cluster_upstream_cx_connect_timeout{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
       "legendFormat": "connection timeout - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_pending_failure_eject{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
       "legendFormat": "pending failure ejection - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_pending_overflow{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
       "legendFormat": "pending overflow - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_timeout{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
       "legendFormat": "request timeout - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_rx_reset{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
       "legendFormat": "response reset by the client - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_tx_reset{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[1m])",
       "legendFormat": "request reset by local Envoy - {{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections to other Dataplanes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_cluster_upstream_cx_active{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Connection time (P99)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, irate(envoy_cluster_upstream_cx_connect_ms_bucket{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m]))",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Connection length (P99)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, irate(envoy_cluster_upstream_cx_length_ms_bucket{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m]))",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Bytes received from other Dataplanes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m])",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Bytes sent to other Dataplanes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m])",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Secured destinations by mTLS",
     "type": "table-old",
     "description": "Data is only available if TrafficPermission policy is applied.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "targets": [
      {
       "expr": "envoy_cluster_ssl_handshake{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"} > 0",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Connection/Requests errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(envoy_cluster_upstream_cx_connect_timeout{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
       "legendFormat": "connection timeout - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_pending_failure_eject{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
       "legendFormat": "pending failure ejection - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_pending_overflow{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
       "legendFormat": "pending overflow - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_timeout{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
       "legendFormat": "request timeout - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_rx_reset{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
       "legendFormat": "request reset by other Envoy - {{envoy_cluster_name}}"
      },
      {
       "expr": "irate(envoy_cluster_upstream_rq_tx_reset{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[1m])",
       "legendFormat": "response reset by local Envoy - {{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.99, rate(envoy_cluster_upstream_rq_time_bucket{kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost_.*\",dataplane=\"$dataplane\"}[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(histogram_quantile(0.95, rate(envoy_cluster_upstream_rq_time_bucket{kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost_.*\",dataplane=\"$dataplane\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "sum(histogram_quantile(0.50, rate(envoy_cluster_upstream_rq_time_bucket{kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost_.*\",dataplane=\"$dataplane\"}[1m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{kuma_io_zone=~\"$zone\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost_.*\",dataplane=\"$dataplane\"}[1m]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{kuma_io_zone=~\"$zone\",mesh=\"$mesh\",dataplane=\"$dataplane\",envoy_cluster_name!~\"localhost_.*\", envoy_cluster_name!=\"kuma_envoy_admin\", envoy_cluster_name!=\"kuma_metrics_hijacker\"}[1m]))",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{kuma_io_zone=~\"$zone\",mesh=\"$mesh\",dataplane=\"$dataplane\", envoy_cluster_name=~\"localhost_.*\"}[1m])) by (envoy_response_code_class)",
     "legendFormat": "Incoming {{envoy_response_code_class}}xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{kuma_io_zone=~\"$zone\",mesh=\"$mesh\",dataplane=\"$dataplane\", envoy_cluster_name!~\"localhost_.*\", envoy_cluster_name!=\"kuma_envoy_admin\", envoy_cluster_name!=\"kuma_metrics_hijacker\"}[1m])) by (envoy_response_code_class)",
     "legendFormat": "Outgoing {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Health Checks - healthy service instances",
     "type": "graph",
     "description": "Data is only available if HealthCheck policy is applied.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_cluster_health_check_healthy{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Active Health Checks - failing service instances",
     "type": "graph",
     "description": "Data is only available if HealthCheck policy is applied.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_cluster_membership_total{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"} - envoy_cluster_health_check_healthy{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thresholds Overflow",
     "type": "graph",
     "description": "Total times that the cluster’s connection circuit breaker overflowed",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_cx_overflow{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m]))",
       "legendFormat": "Connection overflow"
      },
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_pending_overflow{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m]))",
       "legendFormat": "Pending request overflow"
      },
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_retry_overflow{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}[1m]))",
       "legendFormat": "Retry overflow"
      }
     ]
    },
    {
     "title": "Outlier detection",
     "type": "graph",
     "description": "Data is only available if HealthCheck policy is applied. Note that passive health checks are executed on healthy instances marked by active health checks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - sum(envoy_cluster_outlier_detection_ejections_active{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"}) / sum(envoy_cluster_membership_total{dataplane=\"$dataplane\",kuma_io_zone=~\"$zone\",mesh=\"$mesh\"})",
       "legendFormat": "Healthy destinations"
      }
     ]
    }
   ]
  }
 ]
}