ingressController:
  enabled: false
image:
  repository: kong/kong-gateway
  tag: 2.8
env:
  database: "off"
  role: data_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_control_plane: $CLUSTER_URL:8005
  cluster_telemetry_endpoint: $CLUSTER_TELEMETRY_URL:8006
proxy:
  enabled: true
secretVolumes: 
  - kong-cluster-cert
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  portal:
    enabled: false
  rbac:
    enabled: false
  smtp:
    enabled: false
admin:
  enabled: false
manager:
  enabled: false
portal:
  enabled: false
portalapi:
  enabled: false  
podAnnotations:
  "kuma.io/mesh": default
  "kuma.io/gateway": enabled