apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kong-operator-role
rules:
- apiGroups: ["networking.k8s.io"] 
  resources: ["ingressclasses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kong-operator-binding
subjects:
- kind: ServiceAccount
  name: kong-operator
  namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: kong-operator-role
  apiGroup: rbac.authorization.k8s.io