apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: default
metadata:
  name: edge-gateway
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway
  conf:
    listeners:
    - port: 8080
      protocol: HTTP
      tags:
        port: http/8080 
---
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
mesh: default
metadata:
  name: kong-gateway-kuma-demo
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway
        vhost: kong-gateway-svc-kong-mesh-system.apps.temp-lab.kni.syseng.devcluster.openshift.com
  conf:
    http:
      rules:
        - matches:
            - path:
                match: PREFIX
                value: /kuma-demo
          backends:
            - destination:
                kuma.io/service: frontend_kuma-demo_svc_8080
---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway-svc
spec:
  ports:
  - name: gateway
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kong-mesh-control-plane
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-gateway-svc
spec:
  port:
    targetPort: gateway
  to:
    kind: Service
    name: kong-gateway-svc