apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: kong-operator-group
  namespace: kong-keycloak
spec:
  targetNamespaces:
    - kong-keycloak
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: kong-keycloak
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: keycloak-operator.v18.0.0